package patches.projects

import jetbrains.buildServer.configs.kotlin.v2018_2.*
import jetbrains.buildServer.configs.kotlin.v2018_2.Project
import jetbrains.buildServer.configs.kotlin.v2018_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the root project
accordingly, and delete the patch script.
*/
changeProject(DslContext.projectId) {
    features {
        remove {
            feature {
                type = "project-graphs"
                id = "PROJECT_EXT_3"
                param("defaultFilters", "")
                param("format", "text")
                param("hideFilters", "")
                param("series", """
                    [
                      {
                        "type": "valueType",
                        "title": "Build Duration (excluding Checkout Time)",
                        "sourceBuildTypeId": "AngularCliApp_Build",
                        "key": "BuildDurationNetTime"
                      }
                    ]
                """.trimIndent())
                param("seriesTitle", "Serie")
                param("title", "Build Duration")
            }
        }
        add {
            feature {
                type = "project-graphs"
                id = "PROJECT_EXT_8"
                param("series", """
                    [
                      {
                        "type": "valueType",
                        "title": "Build Duration (all stages)",
                        "sourceBuildTypeId": "ViaPipelineAngularCli_03Build",
                        "key": "BuildDuration"
                      }
                    ]
                """.trimIndent())
                param("format", "text")
                param("title", "New chart title")
                param("seriesTitle", "Serie")
            }
        }
    }
}
